baseURL: "https://thenoesis12.netlify.app"
languageCode: "en-us"
title: "The Noesis"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "https://twitter.com/thenoesiske"
  github: "#"
  instagram: "https://instagram.com/thenoesiske"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
