baseURL: "https://thenoesis12.netlify.app"
languageCode: "en-us"
title: "The Noesis"
pygmentsstyle: 'monokai'
enableEmoji: true
paginate: 10
social:
  twitter: "https://twitter.com/thenoesiske"
  github: "#"
  instagram: "https://instagram.com/thenoesiske"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
params:
  description: "Join us as we explore the tech and science world of mysteries"
  images: "images/about.png"
taxonomies:
  author: authors
  tag: tags
  category: categories
markup:
  goldmark:
    renderer:
      unsafe: true
